services:
  sql:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    image: mcr.microsoft.com/mssql/server:2022-latest
    labels:
      com.jetbrains.rider.debug: "false"
    networks: [backend]
    ports: ["1433:1433"]
    healthcheck:
      test: >-
        /opt/mssql-tools18/bin/sqlcmd
        -S localhost
        -P "$$SA_PASSWORD"
        -U sa
        -N o
        -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s

  db-ready:
    depends_on:
      sql:
        condition: service_healthy

networks:
  backend:
    driver: bridge
