version: "3.8"

services:

  frontend:
    build:
      context: .
      dockerfile: src/TrakIt.FrontEnd/Dockerfile
    extends:
      file: docker-compose.base.yml
      service: base
    image: ghcr.io/palletshuttle/frontend:${TAG:-latest}
    networks: [backend]
    ports: ["8080:8080"]

  mapf-api:
    build:
      context: .
      dockerfile: src/TrakIt.MAPF.Api/Dockerfile
    depends_on:
      db-ready:
        condition: service_completed_successfully
    extends:
      file: docker-compose.base.yml
      service: base
    image: ghcr.io/palletshuttle/mapf-api:${TAG:-latest}
    networks: [backend]
    ports: ["8083:8080"]
    env_file: .env

  db-ready:
    build:
      context: .
      dockerfile: src/TrakIt.DatabaseReady/src/Dockerfile
    environment:
      DELETE_DATABASE: ${DELETE_DATABASE:-}
      MAP_SEED_JSON: ${MAP_SEED_JSON:-}
    image: ghcr.io/palletshuttle/db-ready:${TAG:-latest}
    extends:
      file: docker-compose.base.yml
      service: base
    networks: [backend]
    env_file: .env

  shuttle-comms-service:
    build:
      context: .
      dockerfile: src/TrakIt.ShuttleComm.Gateway/src/Dockerfile
    depends_on:
      db-ready:
        condition: service_completed_successfully
    extends:
      file: docker-compose.base.yml
      service: base
    image: ghcr.io/palletshuttle/shuttle-comms-service:${TAG:-latest}
    networks: [backend]
    profiles: [physical]

networks:
  backend:
    driver: bridge
