version: "3.8"

services:
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/remote.Dockerfile
    extends:
      file: docker-compose-base.yml
      service: base
    image: ghcr.io/palletshuttle/rabbitmq-monitor:${TAG:-latest}
    labels:
      com.jetbrains.rider.debug: "false"
    healthcheck:
      test: >-
        rabbitmqadmin show overview
        -H $RabbitMq__HostName
        -u $RabbitMq__UserName
        -p $RabbitMq__Password
      interval: 5s
      timeout: 30s
      retries: 3
